version: "3"

services:
  my_db:
    image: postgres:latest
    container_name: my_db
    ports:
      - 6000:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    volumes:
      - ./db:/var/lib/postgresql/data
      
  my_py_script:
    build:
      context: .
    container_name: my_py_script
    volumes:
      - ./src:/app
    


